Upgrading Jira library to work around Jira API change:
```
JIRAError: JiraError HTTP 410 url:
https://urbanairship.atlassian.net/rest/api/2/search?jql=%28project+%3D+%22ORC%22%29+AND+%28updated+%3E+%222024-01-01%22%29&startAt=0&validateQuery=True&fields
=%2Aall&expand=changelog&maxResults=100
        text: The requested API has been removed. Please migrate to the /rest/api/3/search/jql API. A full migration guideline is available at
https://developer.atlassian.com/changelog/#CHANGE-2046

        response headers = {'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Wed, 17 Sep
2025 17:23:55 GMT', 'Server': 'AtlassianEdge', 'Timing-Allow-Origin': '*', 'X-Arequestid': '9d7f53fcfa972aaaa572935d7cb8a9e7', 'X-Aaccountid':
'557058%3Ad3c50740-6786-48f8-a5f8-a115ed6d7edb', 'Cache-Control': 'no-cache, no-store, no-transform', 'X-Beta-Ratelimit-Limit': '350',
'X-Beta-Ratelimit-Remaining': '348', 'Beta-Retry-After': '1', 'X-Beta-Ratelimit-Reset': '2025-09-17T17:23Z', 'X-Beta-Ratelimit-Reason': 'jira-burst-based',
'X-Content-Type-Options': 'nosniff', 'X-Xss-Protection': '1; mode=block', 'Atl-Traceid': '4a4fdd19a21542fea72f46747119ed2f', 'Atl-Request-Id':
'4a4fdd19-a215-42fe-a72f-46747119ed2f', 'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload', 'Report-To': '{"endpoints": [{"url":
"https://dz8aopenkvv6s.cloudfront.net"}], "group": "endpoint-1", "include_subdomains": true, "max_age": 600}', 'Nel': '{"failure_fraction": 0.001,
"include_subdomains": true, "max_age": 600, "report_to": "endpoint-1"}', 'Server-Timing':
'atl-edge;dur=76,atl-edge-internal;dur=24,atl-edge-upstream;dur=52,atl-edge-pop;desc="aws-us-east-1"', 'X-Cache': 'Error from cloudfront', 'Via': '1.1
ac5e5bbfe147d1cc8d56241c328b6a78.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'ORD58-P6', 'X-Amz-Cf-Id':
'a6q3pfKufkmJZnefkliHkHZowItZhK0M7BE5cTem-MTsBX2K38WpNg=='}
        response text = {"errorMessages":["The requested API has been removed. Please migrate to the /rest/api/3/search/jql API. A full migration guideline is
available at https://developer.atlassian.com/changelog/#CHANGE-2046"],"errors":{}}
```